- platform: generic_thermostat
  name: Kuchnia
  heater: switch.air_condition
  target_sensor: sensor.fan_temperature
  min_temp: 15
  max_temp: 24
  ac_mode: true
  target_temp: 21
  cold_tolerance: 0.3
  hot_tolerance: 0
  min_cycle_duration:
    seconds: 5
  keep_alive:
    minutes: 3
  initial_hvac_mode: "off"
  away_temp: 16
  precision: 0.1
