homeassistant:
  customize: !include customize.yaml

http:
  base_url: https://homeassistant-srokak.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

lovelace:
  mode: yaml

frontend:
  themes: !include themes.yaml

tts:
  - platform: google_translate

config:
history:
logbook:
map:
mobile_app:
ssdp:
sun:
system_health:
updater:
zeroconf:
recorder:
  purge_keep_days: 2

person: !include persons.yaml
automation: !include automations.yaml
script: !include scripts.yaml
binary_sensor: !include binary_sensor.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
light: !include lights.yaml
group: !include groups.yaml
device_tracker: !include device_tracker.yaml
climate: !include climate.yaml
notify: !include notify.yaml
input_text: !include input_text.yaml
input_number: !include input_number.yaml
input_boolean: !include input_boolean.yaml
# input_select: !include input_select.yaml
zone: !include zone.yaml

owntracks:
  max_gps_accuracy: 100
  waypoints: true
  mqtt_topic: "owntracks/#"
  events_only: false
  waypoint_whitelist:
    - Krzysiek
    - Aga

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    pending_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0

telegram_bot:
  - platform: polling
    api_key: !secret tlegram_api_key
    allowed_chat_ids:
      - !secret xiaomi
      - !secret galaxy

spotify:
  client_id: 5ea363fa525c48359845164024d63886
  client_secret: !secret spotify
  
timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 600 # Updated this to the number of seconds you wish

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret InfluxDB
  max_retries: 3
  default_measurement: state

zigbee2mqtt_networkmap:

panel_iframe:
  zwave2mqtt:
    title: Z-Wave to MQTT
    icon: mdi:z-wave
    url: https://homeassistant-srokak.duckdns.org:8091
    
  networkmap:
    title: Zigbee Map
    url: /local/community/zigbee2mqtt_networkmap/map.html
    icon: mdi:graphql

shell_command:
  disco_off: echo -e -n "\x01\x08\x00\xF2\x51\x01\x00\x05\x01\x51" > /dev/serial/by-id/usb-0658_0200-if00
  disco_on: echo -e -n "\x01\x08\x00\xF2\x51\x01\x01\x05\x01\x50" > /dev/serial/by-id/usb-0658_0200-if00 