esphome:
  name: bluetooth_hub_goscinny
  platform: ESP32
  board: wemosbat

wifi:
  ssid: "FRITZ!Box_7430_MX"
  password: "grzesieks15261526"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  # ap:
  #   ssid: "Bluetooth Hub Fallback Hotspot"
  #   password: "H6R9hdN82amx"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

esp32_ble_tracker:
  
sensor:
  - platform: xiaomi_hhccjcy01
    mac_address: C4:7C:8D:6B:29:8E
    temperature:
      name: "Xiaomi MiFlora Temperature"
    moisture:
      name: "Xiaomi MiFlora Moisture"
    illuminance:
      name: "Xiaomi MiFlora Illuminance"
    conductivity:
      name: "Xiaomi MiFlora Soil Conductivity"
    battery_level:
      name: "Xiaomi MiFlora Battery Level"
      
  - platform: xiaomi_lywsdcgq
    mac_address: 58:2D:34:39:2D:F7
    temperature:
      name: "Living Room Sensor Temperature"
    humidity:
      name: "Living Room Sensor Humidity"
    battery_level:
      name: "Living Room Sensor Battery Level"